SELECT ?language ?license ?spatial ?tstart ?tend
?format ?desc
((group_concat(distinct ?themeLabel ; separator = ",")) as ?themes)
((group_concat(distinct ?kw ; separator = ",")) as ?keywords)
((group_concat(distinct ?motiv ; separator = ",")) as ?motivations)
((group_concat(distinct ?content ; separator = ",")) as ?natureOfContent) ?name ?homepage
?licenseLabel ?licenseText
WHERE {
	<%%id%%> a <https://www.w3id.org/dso#DataRequest> ;
	<https://www.w3id.org/dso#language> ?language ;
	<https://www.w3id.org/dso#mediaType> ?format ;
	<https://www.w3id.org/dso#description> ?desc ;
	<https://www.w3id.org/dso#theme> [
		a <http://www.w3.org/2008/05/skos#Concept> ;
		<http://www.w3.org/2008/05/skos#prefLabel> ?themeLabel ] ;
	<https://www.w3id.org/dso#keyword> ?kw ;
	<https://www.w3id.org/dso#submitter> [
		<http://xmlns.com/foaf/0.1/name> ?name ;
		<http://xmlns.com/foaf/0.1/homepage> ?homepage 	 ] .

		OPTIONAL{ <%%id%%> <https://www.w3id.org/dso#license> ?license

		GRAPH <http://purl.org/NET/rdflicense/> {
			?license <http://www.w3.org/2000/01/rdf-schema#label> ?licenseLabel .
			?license <http://creativecommons.org/ns#legalcode> ?licenseText .
		}

		} .
		OPTIONAL{ <%%id%%> <https://www.w3id.org/dso#requestContent> ?cnt} .
		OPTIONAL{ <%%id%%> <https://www.w3id.org/dso#spatialRange> ?spatial } .
		OPTIONAL{ <%%id%%> <https://www.w3id.org/dso#temporalRange> [
        a <http://purl.org/dc/terms/PeriodOfTime> ;
        <http://schema.org/startDate> ?tstart ;
        <http://schema.org/endDate> ?tend
    ] } .
		OPTIONAL{ <%%id%%> <https://www.w3id.org/dso#motivation> ?motiv } .

			GRAPH <https://www.w3id.org/dso#> {
				?cnt a <http://www.w3.org/2008/05/skos#Concept> .
				?cnt <http://www.w3.org/2008/05/skos#prefLabel> ?content .
			}
} GROUP BY
?language ?license ?spatial ?tstart
?tend ?format ?desc ?themes ?keywords
?motivations ?natureOfContent ?name ?homepage
?licenseLabel ?licenseText 
